
CREATE TABLE PRODUCTS_1 (
PRODUCT_ID int NOT NULL AUTO_INCREMENT,
PRODUCT_NAME varchar(200) NOT NULL,
PRODUCT_TYPE varchar(45) NOT NULL,
PRICE decimal(10,2) NOT NULL,
QUANTITY int NOT NULL default 0,
PRIMARY KEY (PRODUCT_ID)
) ENGINE=InnoDB;

alter table PRODUCTS_1 ADD CONSTRAINT PRODUCTS_ISBN UNIQUE (ISBN);
