
-- please check my data modelling lesson to see how I create ECOMM_STORE schema

use ECOMM_STORE;


CREATE TABLE PRODUCTS_1 (
PRODUCT_ID int NOT NULL AUTO_INCREMENT,
PRODUCT_NAME varchar(200) NOT NULL,
PRODUCT_TYPE varchar(45) NOT NULL,
PRICE decimal(10,2) NOT NULL,
QUANTITY int NOT NULL default 0,
PRIMARY KEY (PRODUCT_ID),
UNIQUE KEY PRODUCT_NAME_UNIQUE (PRODUCT_NAME)
) ENGINE=InnoDB;
